#include<stdio.h>
using namespace std;
int a[100][100];//
int in,ax=0,bx,ex;//ax=heng;bx=lie;in=shu'ru;a=shu'zu;
int main(){
	scanf("%d",&in);
	while(true){
		bx=0;
		while(true){
			scanf("%d",&a[ax][bx]);
			bx++;
			if(bx==in)break;
		}
		ax++;
		if(ax==in)break;
	}
	ax=0;
	while(true){
		printf("%d\n",a[1][1]);
		while(true){
			bx=0;
			while(true){
				if(a[ax][bx]>a[ax][bx+1])ex=a[ax][bx];
				else ex=a[ax][bx+1];
				bx++;
				if(bx<in)break;
			}
			bx=0;
			while(true){
				a[ax][bx]-=ex;
				bx++;
				if(bx==in)break;
			}
			ax++;
			if(ax==in)break;
		}
		bx=0;
		while(true){
			ax=0;
			while(true){
				if(a[ax][bx]>a[ax+1][bx])ex=a[ax][bx];
				else ex=a[ax+1][bx];
				ax++;
				if(ax<in)break;
			}
			ax=0;
			while(true){
				a[ax][bx]-=ex;
				ax++;
				if(ax==in)break;
			}
			bx++;
			if(bx==in)break;
		}
		ax=0;
		while(true){
			bx=1;
			while(true){
				if(bx<in)break;
				a[ax][bx]=a[ax][bx+1];
				bx++;
			}
			a[ax][in]=0;
			ax++;
			if(ax==in)break;
		}
		bx=0;
		while(true){
			ax=1;
			while(true){
				if(ax<in)break;
				a[ax][bx]=a[ax+1][bx];	
				ax++;
			}
			a[in][bx]=0;
			bx++;
			if(bx==in)break;
		}
		in--1;
		if(in==1)break;
	}
	printf("0\n");
	return 0;
} 
